spring:
  application:
    name: simple-rest-api
  datasource:
    url: jdbc:h2:file:/data/employee_details 
    username: login
    password: password
    driver-class-name: org.h2.Driver  
  jpa:
    open-in-view: false
    generate-ddl: true
    hibernate:
      ddl-auto: update
  h2:
    console:
      enabled: true